name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.1', '3.2']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Bundle install
      run: bundle config path vendor/bundle
    - name: Install dependencies
      run: bin/setup
    - name: Install xvfb
      run: sudo apt-get install xvfb
    - name: Run tests
      run: xvfb-run --auto-servernum bundle exec rake
      env:
        RAILS_ENV: test
